# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: yamagh
email: yamagh@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  愛媛のSIerではたらくしがないエンジニア。好きな言語は Ruby。
  そのほかいろいろ。競技プログラミング(yukicoder, paiza, code-iq), 写真(Sony 
  Nex-3N, Theta S), House Music, Podcast(Backspace.fm, rebuild.fm ...)。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: _yama
github_username:  yamagh

# Build settings
markdown: kramdown

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
    tracking_id : 'UA-51327309-5'
  getclicky :
    site_id :

