# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "yamagh's blog"
email: yamagh@outlook.com
description: > # this means to ignore newlines until "baseurl:"
    愛媛ではたらくしがないエンジニアが綴る日常のブログ。
    最近人生に迷い気味。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: _yama
github_username:  yamagh

# Build settings
markdown: kramdown

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
    tracking_id : 'UA-51327309-5'
#  getclicky :
#    site_id :

